# -*- mode: ruby -*-
# vi: set ft=ruby :


Vagrant.configure("2") do |config|

  config.vm.box = "geerlingguy/ubuntu1604"
  config.ssh.insert_key = false

  config.vm.provider :virtualbox do |v|
    v.name = "kub2"
    v.memory = 1024
    v.cpus = 2
  end

  config.vm.hostname = "kub2"
  config.vm.network :private_network, ip: "17.21.0.16"

  config.vm.define :kub2 do |kub2|
  end

  # Ansible provisioner.
  config.vm.provision "ansible" do |ansible|
    ansible.compatibility_mode = "2.0"
    ansible.playbook = "kub2.yml"
    ansible.become = true
  end
end
