---
- name: Enable the br_netfilter module for cluster communication.
  modprobe:
    name: br_netfilter
    state: present

- name: Disable swap
  command: swapoff -a

- name: Remove swapfile from /etc/fstab
  mount:
    name: swap
    fstype: swap
    state: absent

- name: Copying K8s repo
  become: yes
  command: apt-add-repository "deb http://apt.kubernetes.io/ kubernetes-xenial main"

- name: Installing kube repo key
  apt_key:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    state: present

- name: Installing kubernetes-cni
  apt:
    name: kubernetes-cni
    state: present
    update_cache: yes

- name: Installing Kubelet
  yum:
    name: kubelet
    state: present
    update_cache: yes

- name: Installing Kubeadm
  yum:
    name: kubeadm
    state: present
    update_cache: yes

- name: Installing Kubectl
  yum:
    name: kubectl
    state: present
    update_cache: yes