# -*- mode: ruby -*-
# vi: set ft=ruby :


Vagrant.configure("2") do |config|
  
  config.vm.box = "centos/7"
  config.ssh.insert_key = false

  config.vm.provider :virtualbox do |v|
    v.name = "kub3"
    v.memory = 1024
    v.cpus = 2
  end

  config.vm.hostname = "kub3"
  config.vm.network :private_network, ip: "17.21.0.17"

  config.vm.define :kub3 do |kub3|
  end

  # Ansible provisioner.
  config.vm.provision "ansible" do |ansible|
    ansible.compatibility_mode = "2.0"
    ansible.playbook = "kub3.yml"
    ansible.become = true
  end
end
