# -*- mode: ruby -*-
# vi: set ft=ruby :


Vagrant.configure("2") do |config|

  config.vm.box = "centos/7"
  config.ssh.insert_key = false

  config.vm.provider :virtualbox do |v|
    v.name = "kub1"
    v.memory = 2048
    v.cpus = 2
  end

  config.vm.hostname = "kub1"
  config.vm.network :private_network, ip: "17.21.0.15"

  config.vm.define :kub1 do |kub1|
  end

  # Ansible provisioner.
  config.vm.provision "ansible" do |ansible|
    ansible.compatibility_mode = "2.0"
    ansible.playbook = "kub1.yml"
    ansible.become = true
  end

end
